FROM kmgreen2/ethereum-base:latest

COPY service/ethereum/genesis.json $ETH_DATA_DIR/
COPY service/ethereum/keystore.json $ETH_DATA_DIR/
COPY service/ethereum/start_membernode.sh /

EXPOSE $ETH_PORT $ETH_RPC_PORT
