FROM kmgreen2/ethereum-base:latest

COPY service/ethereum/genesis.json $ETH_DATA_DIR/
COPY service/ethereum/boot.key $ETH_DATA_DIR/
COPY service/ethereum/start_bootnode.sh /
COPY service/enode_server/enode_server.go /

EXPOSE $ETH_BOOT_PORT
