FROM golang:1.9.2

RUN apt-get update
RUN apt-get install dnsutils -y
RUN apt-get install wget -y
RUN apt-get install netcat -y
RUN apt-get install net-tools -y
RUN apt-get install vim -y
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install nodejs -y

WORKDIR /root

RUN git clone https://github.com/cubedro/eth-net-intelligence-api

WORKDIR /root/eth-net-intelligence-api

RUN npm install
RUN npm install -g pm2

# Create logdir
RUN mkdir -p /var/log/ethereum

COPY service/ethereum/start_ethnet_agent.sh /
COPY config/ethereum/ethnet-agent-app.json /root/eth-net-intelligence-api/app.json
