FROM centos:7

RUN yum update -y
RUN yum install -y python
RUN yum install -y curl
RUN yum install -y nc
RUN yum install -y net-tools
RUN yum install -y wget
RUN yum install -y bash
RUN yum install -y vim

ENV VISUAL=vim
ENV EDITOR=vim

COPY ./service/echoserver/echo_server.py /

