apiVersion: v1
kind: Namespace
metadata:
  name: echoserver
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: echoserver
  namespace: echoserver
spec:
  selector:
    matchLabels:
      app: echoserver
  replicas: 2
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - name: echoserver
        imagePullPolicy: Always
        image: "docker.io/kmgreen2/sl7-echoserver:latest"
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
        ports:
        - containerPort: 1337
          name: server
        command:
        - sh
        - -c
        - "python echo_server.py"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "echo | nc --send-only -v -u -w5 localhost 1337"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "echo | nc --send-only -v -u -w5 localhost 1337"
          initialDelaySeconds: 10
          timeoutSeconds: 5
      securityContext:
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: echoserver
  labels:
    app: echoserver
spec:
  ports:
  - port: 1337
    name: echoserver-client
    protocol: TCP
  selector:
    app: echoserver
  type: LoadBalancer
